# Generated by Django 4.2.4 on 2023-08-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
