# Generated by Django 4.2.4 on 2023-08-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_comment_name_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
