# Generated by Django 4.2.4 on 2023-08-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
