# Generated by Django 4.2.4 on 2023-08-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_filter_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True)),
                ('u_id', models.IntegerField(null=True)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
