# Generated by Django 4.2.4 on 2023-08-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='E:\\Web\\my_sale_web\\file_upload'),
        ),
    ]
