# Generated by Django 4.2.4 on 2023-08-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_alter_file_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='u_id',
        ),
        migrations.AddField(
            model_name='file',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
