# Generated by Django 4.2.4 on 2023-08-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_remove_file_u_id_file_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='E:\\Web\\my_sale_web\\static'),
        ),
    ]
