# Generated by Django 4.2.4 on 2024-05-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_alter_file_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='filter',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
